alter table public.activity_feed add constraint activity_feed_pkey PRIMARY KEY (id);
alter table public.billing_credits add constraint billing_credits_pkey PRIMARY KEY (id);
alter table public.booking_reminders add constraint booking_reminders_pkey PRIMARY KEY (id);
alter table public.bookings add constraint bookings_pkey PRIMARY KEY (id);
alter table public.client_sessions add constraint client_sessions_pkey PRIMARY KEY (id);
alter table public.contacts add constraint contacts_pkey PRIMARY KEY (user_id, caller_phone);
alter table public.link_clicks add constraint link_clicks_pkey PRIMARY KEY (click_id);
alter table public.loyalty_rewards add constraint loyalty_rewards_pkey PRIMARY KEY (id);
alter table public.message_templates add constraint message_templates_pkey PRIMARY KEY (id);
alter table public.missed_calls add constraint missed_calls_pkey PRIMARY KEY (id);
alter table public.missed_calls_log add constraint missed_calls_log_pkey PRIMARY KEY (call_id);
alter table public.opt_outs add constraint opt_outs_pkey PRIMARY KEY (user_id, caller_phone);
alter table public.phone_numbers add constraint phone_numbers_pkey PRIMARY KEY (phone);
alter table public.portfolio_photos add constraint portfolio_photos_pkey PRIMARY KEY (id);
alter table public.referrals add constraint referrals_pkey PRIMARY KEY (id);
alter table public.services add constraint services_pkey PRIMARY KEY (id);
alter table public.short_links add constraint short_links_pkey PRIMARY KEY (code);
alter table public.sms_log add constraint sms_log_pkey PRIMARY KEY (id);
alter table public.sticker_codes add constraint sticker_codes_pkey PRIMARY KEY (code);
alter table public.sticker_scans add constraint sticker_scans_pkey PRIMARY KEY (id);
alter table public.users add constraint users_pkey PRIMARY KEY (user_id);
alter table public.vip_clients add constraint vip_optins_pkey PRIMARY KEY (id);
alter table public.visit_closeouts add constraint visit_closeouts_pkey PRIMARY KEY (visit_key);
alter table public.billing_credits add constraint billing_credits_referral_id_user_id_key UNIQUE (referral_id, user_id);
alter table public.booking_reminders add constraint booking_reminders_booking_id_reminder_type_key UNIQUE (booking_id, reminder_type);
alter table public.client_sessions add constraint client_sessions_token_hash_key UNIQUE (token_hash);
alter table public.loyalty_rewards add constraint loyalty_rewards_visit_key_key UNIQUE (visit_key);
alter table public.message_templates add constraint message_templates_user_id_template_key_key UNIQUE (user_id, template_key);
alter table public.phone_numbers add constraint phone_numbers_assigned_user_id_key UNIQUE (assigned_user_id);
alter table public.referrals add constraint referrals_referred_user_id_key UNIQUE (referred_user_id);
alter table public.users add constraint users_phone_number_key UNIQUE (phone_number);
alter table public.vip_clients add constraint vip_clients_user_phone_unique UNIQUE (user_id, phone_number);
alter table public.billing_credits add constraint billing_credits_amount_check CHECK ((amount > 0));
alter table public.billing_credits add constraint billing_credits_kind_check CHECK ((kind = ANY (ARRAY['free_month'::text, 'percent_off'::text])));
alter table public.booking_reminders add constraint booking_reminders_reminder_type_check CHECK ((reminder_type = ANY (ARRAY['confirmation'::text, '24h'::text, '2h'::text, 'review'::text])));
alter table public.bookings add constraint bookings_status_check CHECK ((status = ANY (ARRAY['confirmed'::text, 'cancelled'::text, 'completed'::text, 'no_show'::text])));
alter table public.client_sessions add constraint client_sessions_kind_check CHECK ((kind = ANY (ARRAY['session'::text, 'link'::text])));
alter table public.contacts add constraint contacts_notes_length CHECK (((notes IS NULL) OR (length(notes) <= 1000)));
alter table public.missed_calls_log add constraint missed_calls_log_status_check CHECK ((status = ANY (ARRAY['logged'::text, 'pending_reply'::text, 'sms_sent'::text, 'failed'::text])));
alter table public.referrals add constraint referrals_check CHECK ((referrer_user_id <> referred_user_id));
alter table public.referrals add constraint referrals_status_check CHECK ((status = ANY (ARRAY['signed_up'::text, 'qualified'::text])));
alter table public.sms_log add constraint sms_log_direction_check CHECK ((direction = ANY (ARRAY['outbound'::text, 'inbound'::text])));
alter table public.sms_log add constraint sms_log_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'dev'::text, 'failed'::text, 'received'::text])));
alter table public.sticker_codes add constraint sticker_codes_status_check CHECK ((status = ANY (ARRAY['unclaimed'::text, 'active'::text, 'retired'::text])));
alter table public.users add constraint users_call_mode_check CHECK ((call_mode = ANY (ARRAY['forwarded'::text, 'direct'::text])));
alter table public.users add constraint users_carrier_check CHECK ((carrier = ANY (ARRAY['tmobile'::text, 'att'::text, 'verizon'::text, 'other'::text])));
alter table public.users add constraint users_loyalty_reward_cents_check CHECK (((loyalty_reward_cents >= 100) AND (loyalty_reward_cents <= 5000)));
alter table public.users add constraint users_missed_call_style_check CHECK ((missed_call_style = ANY (ARRAY['casual'::text, 'professional'::text, 'custom'::text])));
alter table public.users add constraint users_plan_check CHECK ((plan = ANY (ARRAY['basic'::text, 'full'::text])));
alter table public.users add constraint users_slug_format CHECK (((slug IS NULL) OR (slug ~ '^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])$'::text)));
alter table public.users add constraint users_theme_check CHECK ((theme = ANY (ARRAY['classic'::text, 'mint'::text, 'gold'::text, 'midnight'::text, 'cream'::text])));
alter table public.vip_clients add constraint vip_clients_language_supported CHECK ((client_language = ANY (ARRAY['en'::text, 'es'::text, 'pt'::text])));
alter table public.vip_clients add constraint vip_clients_optin_requires_proof CHECK (((is_opted_in = false) OR ((opted_in_at IS NOT NULL) AND (consent_text IS NOT NULL))));
alter table public.billing_credits add constraint billing_credits_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id) ON DELETE SET NULL;
alter table public.billing_credits add constraint billing_credits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
alter table public.booking_reminders add constraint booking_reminders_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
alter table public.bookings add constraint bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE CASCADE;
alter table public.bookings add constraint bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.contacts add constraint contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
alter table public.link_clicks add constraint link_clicks_call_id_fkey FOREIGN KEY (call_id) REFERENCES public.missed_calls_log(call_id);
alter table public.loyalty_rewards add constraint loyalty_rewards_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;
alter table public.message_templates add constraint message_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
alter table public.missed_calls add constraint missed_calls_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
alter table public.opt_outs add constraint opt_outs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
alter table public.phone_numbers add constraint phone_numbers_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;
alter table public.referrals add constraint referrals_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
alter table public.referrals add constraint referrals_referrer_user_id_fkey FOREIGN KEY (referrer_user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
alter table public.services add constraint services_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.sticker_codes add constraint sticker_codes_handed_out_by_fkey FOREIGN KEY (handed_out_by) REFERENCES auth.users(id);
alter table public.sticker_codes add constraint sticker_codes_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(user_id);
alter table public.sticker_scans add constraint sticker_scans_code_fkey FOREIGN KEY (code) REFERENCES public.sticker_codes(code);
alter table public.users add constraint users_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES public.users(user_id) ON DELETE SET NULL;
alter table public.vip_clients add constraint vip_optins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
